# Checks for uncommitted changes to built files and pushes changes back.
name: Check built files

on:
  # Because all commits happen through SVN and should always be manually reviewed by a committer, this workflow only
  # runs for pull requests.
  #
  # Other workflows that run on push will detect changes to versioned files and fail.
  pull_request_target:
    branches:
      - trunk
      - '6.[8-9]'
      - '[7-9].[0-9]'
    paths:
      # Any change to a CSS, JavaScript, JSON, or SASS file should run checks.
      - '**.css'
      - '**.js'
      - '**.json'
      - '**.sass'
      # These files configure npm and the task runner. Changes could affect the outcome.
      - 'package*.json'
      - 'Gruntfile.js'
      - 'webpack.config.js'
      - 'tools/webpack/**'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # Confirm any changes to relevant workflow files.
      - '.github/workflows/check-built-files.yml'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  update-built-files:
    name: Update built files
    permissions:
      contents: write
    if: ${{ github.repository == 'WordPress/wordpress-develop' }}
    # This should always reference a version of the workflow committed through SVN and never a local reference.
    uses: WordPress/wordpress-develop/.github/workflows/reusable-check-built-files.yml@trunk
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
